version: '3.1'

services:
  app:
    image: 'address-book:0.0.1'
    build:
      context: .
    container_name: address-book
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/addressbook
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=3ZEXR4HYLG7ABNM5
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=addressbook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3ZEXR4HYLG7ABNM5